/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getV1Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List IDEs/agents for composer */
        get: operations["listV1Ides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stacks for directory and homepage cards */
        get: operations["listV1Stacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks/{stackSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stack overview by slug */
        get: operations["getV1StackBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks/{stackSlug}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stack security overview (grades, coverage, framework, threat matrix) */
        get: operations["getV1StackOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stacks/{stackSlug}/policy-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy templates linked to a stack (composer presets) */
        get: operations["listV1PolicyTemplatesByStack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent catalog sync / pipeline runs */
        get: operations["listV1SyncLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threat catalog entries */
        get: operations["listV1Threats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated rules directory */
        get: operations["listV1Rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rules/{ruleSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule detail by slug */
        get: operations["getV1RuleBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/composer/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a merged rules export for stack, IDE, and optional layers */
        post: operations["postV1ComposerExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /**
             * Format: uri
             * @description RFC 7807 problem type URI
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Stack: {
            id: number;
            slug: string;
            name: string;
            logoPath?: string | null;
            sortOrder: number;
            /**
             * @description launch stacks ship in MVP UI; coming_soon are placeholders for contributions
             * @enum {string}
             */
            catalogStatus: "launch" | "coming_soon";
        };
        Ide: {
            id: number;
            slug: string;
            name: string;
            sortOrder: number;
        };
        IdeListResponse: {
            items: components["schemas"]["Ide"][];
        };
        StackListResponse: {
            items: components["schemas"]["Stack"][];
        };
        StackDetail: components["schemas"]["Stack"] & {
            /** @description Rules linked to this stack */
            ruleCount?: number;
        };
        Threat: {
            publicId: string;
            /** @enum {string} */
            family: "owasp_web" | "owasp_llm" | "mitre_atlas" | "vibe_coding";
            name: string;
            severity?: string | null;
            description?: string | null;
            cveId?: string | null;
            externalId?: string | null;
            source?: string | null;
            sourceUrl?: string | null;
            isActivelyExploited?: boolean;
            owaspRefs?: string[];
        };
        ThreatListResponse: {
            items: components["schemas"]["Threat"][];
        };
        Rule: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            version: string;
            certified: boolean;
            lineCount?: number | null;
            /** @description Sum of weekly copy counts from rule_weekly_usage (0 when empty) */
            weeklyUses: number;
        };
        RuleListResponse: {
            items: components["schemas"]["Rule"][];
            /** @description Opaque cursor for next page; null when no more results */
            nextCursor?: string | null;
        };
        /**
         * @description Guardrail layer (matches DB rule_layer enum)
         * @enum {string}
         */
        RuleLayer: "security" | "architecture" | "code_quality";
        RuleLinkedThreat: {
            /** @description Threat primary id (often same as CVE id) */
            publicId: string;
            cveId?: string | null;
            name: string;
            /** @description Advisory or NVD reference URL when stored in DB */
            sourceUrl?: string | null;
        };
        RuleDetail: components["schemas"]["Rule"] & {
            weeklyUses?: number;
            /** @description Markdown body for display or export */
            bodyMdx?: string | null;
            /** @description Layers tagged on this rule */
            layers?: components["schemas"]["RuleLayer"][];
            /** @description CVEs / advisories linked via rule_threat_map for trust badges */
            linkedThreats?: components["schemas"]["RuleLinkedThreat"][];
        };
        ComposerExportRequest: {
            stackSlug: string;
            ideSlug: string;
            /** @description If empty, all rules matching stack+ide are included; if set, rule must include every listed layer */
            layers?: components["schemas"]["RuleLayer"][];
        };
        ComposerExportResponse: {
            /** @enum {string} */
            format: "markdown";
            content: string;
            filename: string;
        };
        /** @enum {string} */
        FrameworkFeatureStatus: "built_in" | "manual_cfg" | "not_supported";
        StackCoverageArea: {
            areaName: string;
            coveragePercent?: number | null;
            notes?: string | null;
        };
        StackFrameworkFeature: {
            featureName: string;
            status: components["schemas"]["FrameworkFeatureStatus"];
            notes?: string | null;
        };
        ThreatMatrixRow: {
            publicId: string;
            name: string;
            severity: string;
            isMitigatedByRules: boolean;
            family: string;
        };
        StackOverviewResponse: {
            id: number;
            slug: string;
            name: string;
            logoPath?: string | null;
            sortOrder: number;
            ruleCount: number;
            securityGrade?: string | null;
            gradeRationale?: string | null;
            ecosystem?: string | null;
            nvdKeywords?: string[];
            osvEcosystem?: string | null;
            coverageAreas: components["schemas"]["StackCoverageArea"][];
            frameworkFeatures: components["schemas"]["StackFrameworkFeature"][];
            threatMatrix: components["schemas"]["ThreatMatrixRow"][];
        };
        PolicyTemplate: {
            id: number;
            slug: string;
            name: string;
            description?: string | null;
            layer: components["schemas"]["RuleLayer"];
            sortOrder: number;
        };
        PolicyTemplateListResponse: {
            items: components["schemas"]["PolicyTemplate"][];
        };
        SyncLogEntry: {
            id: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            coveragePercent?: number | null;
            status: string;
            errorMessage?: string | null;
            sourceSummary: {
                [key: string]: unknown;
            };
        };
        SyncLogListResponse: {
            items: components["schemas"]["SyncLogEntry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getV1Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listV1Ides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IDEs ordered by sortOrder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdeListResponse"];
                };
            };
        };
    };
    listV1Stacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stacks ordered by sortOrder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackListResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getV1StackBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stackSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stack detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackDetail"];
                };
            };
            /** @description Unknown stack */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getV1StackOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stackSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackOverviewResponse"];
                };
            };
            /** @description Unknown stack */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listV1PolicyTemplatesByStack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stackSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Templates ordered by sortOrder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyTemplateListResponse"];
                };
            };
        };
    };
    listV1SyncLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest sync_log rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncLogListResponse"];
                };
            };
        };
    };
    listV1Threats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Threats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatListResponse"];
                };
            };
        };
    };
    listV1Rules: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                /** @description When set, only rules linked to this stack (ordered by rule id) */
                stackSlug?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListResponse"];
                };
            };
            /** @description Invalid pagination or unknown stack */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getV1RuleBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule with optional markdown body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Unknown rule */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    postV1ComposerExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComposerExportRequest"];
            };
        };
        responses: {
            /** @description Export payload (download client-side) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComposerExportResponse"];
                };
            };
            /** @description Invalid request or unknown stack/ide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
